{{- with .Values.kafka }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ .name }}
spec:
  replicas: {{ .replicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .storage }}Gi
        kraftMetadata: shared
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  template:
    persistentVolumeClaim:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
{{- end }}
