---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.rootWind.name }}
  namespace: {{ .Values.global.argocdNamespace }}
  annotations:
    serenditree.io/wave: {{ .Values.rootWind.wave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repository | quote }}
    path: "{{ .Values.global.rootPath }}/{{ trimPrefix .Values.global.rootPrefix .Values.rootWind.name }}"
    targetRevision: {{ .Values.rootWind.revision | default .Values.global.revision | quote }}
    helm:
      parameters:
        - name: global.wait
          value: {{ .Values.global.wait | quote }}
        - name: global.wave
          value: {{ .Values.rootWind.wave | quote }}
        - name: global.context
          value: {{ .Values.global.context }}
  destination:
    server: {{ .Values.global.destinationServer }}
    namespace: {{ .Values.rootSeed.namespace }}
  syncPolicy:
    automated: {{ .Values.global.automated | toYaml | nindent 6 }}
    retry: {{ .Values.global.retry | toYaml | nindent 6  }}
    syncOptions:
      - CreateNamespace=true
