#file: noinspection HelmChartUnknownValues
apiVersion: v2
type: application
name: leaf
description: Angular/Nginx frontend resources.
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: commons
    repository: oci://quay.io/serenditree/charts
    version: 0.0.1
