{{- if .Values.terraScale.clusterAutoscaler }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-exoscale-cluster-autoscaler
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-exoscale-cluster-autoscaler
    template:
      data:
        api-zone: "{{ .Values.global.zone.compute1 }}"
        api-key: "{{ `{{ .api-key }}` }}"
        api-secret: "{{ `{{ .api-secret }}` }}"
  data:
    - secretKey: api-key
      remoteRef:
        key: serenditree/scaler/access
        property: value
    - secretKey: api-secret
      remoteRef:
        key: serenditree/scaler/secret
        property: value
{{- end }}
