---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: root-seed
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: root-seed
  data:
    - secretKey: s3.client.default.access_key
      remoteRef:
        key: serenditree/iam/backup-seed/access
        property: value
    - secretKey: s3.client.default.secret_key
      remoteRef:
        key: serenditree/iam/backup-seed/secret
        property: value
