load_module modules/ngx_otel_module.so;

events {
    worker_connections 1024;
}

http {

    otel_exporter {
        endpoint $OTEL_HOST:$OTEL_PORT;
    }

    otel_trace              $OTEL_ENABLED;
    otel_service_name       $OTEL_SERVICE;
    otel_span_name          $OTEL_SPAN;
    otel_trace_context      propagate;

    log_format              main '[$time_local] '
                                 '"$request" $status $body_bytes_sent "$http_referer" '
                                 '"$http_user_agent" "$http_x_forwarded_for"';

    include                 mime.types;
    default_type            application/octet-stream;
    gzip                    on;
    gzip_proxied            any;
    gzip_types              "*";
    server_tokens           off;
    sendfile                on;
    tcp_nopush              on;

    server {
        listen      8080;
        listen      [::]:8080;
        server_name leaf;
        root        $SERENDITREE_CONTENT;
        index       index.html;

        location / {
            set $csp_nonce $request_id;

            add_header Content-Security-Policy "default-src 'self' 'nonce-$csp_nonce'; worker-src 'self' blob:; img-src 'self' data:; frame-ancestors 'none'; object-src 'none'; upgrade-insecure-requests;";
            add_header Referrer-Policy "no-referrer";
            add_header Strict-Transport-Security "max-age=$SERENDITREE_HSTS; includeSubDomains";
            add_header X-Content-Type-Options "nosniff";
            add_header X-Frame-Options "deny";
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Serenditree-Stage "$SERENDITREE_STAGE";

            sub_filter_types  text/html;
            sub_filter_once   off;
            sub_filter        'nonce-x-serenditree' '$csp_nonce';

            try_files $uri $uri/ /index.html;
        }

        location ~ \.mjs$ {
            default_type text/javascript;

            try_files $uri =404;
        }

        location ~ /\. {
            deny all;
        }
    }
}
