{
 "title": "1 Serenditree / Resources",
 "tags": [
  "kubernetes",
  "pods",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Over Time (millicores)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) * 1000",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (container_memory_working_set_bytes{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}) / 1024 / 1024",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Resource Usage - All Pods",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time((sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) * 1000)[$__range:1m])",
     "legendFormat": "CPU Avg"
    },
    {
     "expr": "max_over_time((sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) * 1000)[$__range:1m])",
     "legendFormat": "CPU Max"
    },
    {
     "expr": "min_over_time((sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) * 1000)[$__range:1m])",
     "legendFormat": "CPU Min"
    },
    {
     "expr": "avg_over_time((sum by (namespace, pod) (container_memory_working_set_bytes{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}) / 1024 / 1024)[$__range:1m])",
     "legendFormat": "Memory Avg"
    },
    {
     "expr": "max_over_time((sum by (namespace, pod) (container_memory_working_set_bytes{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}) / 1024 / 1024)[$__range:1m])",
     "legendFormat": "Memory Max"
    },
    {
     "expr": "min_over_time((sum by (namespace, pod) (container_memory_working_set_bytes{pod=~\"$pod\", namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}) / 1024 / 1024)[$__range:1m])",
     "legendFormat": "Memory Min"
    }
   ]
  }
 ]
}