########################################################################################################################
# Quarkus
########################################################################################################################
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: root-user
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: root-user
    template:
      data:
        database-name: "{{ .Values.rootUser.db.name }}"
        database-user: "{{ `{{ .database_user }}` }}"
        database-password: "{{ `{{ .database_password }}` }}"
        database-root-password: "{{ `{{ .database_root_password }}` }}"
  data:
    - secretKey: database_user
      remoteRef:
        key: serenditree/app/rootUser/db/user
        property: value
    - secretKey: database_password
      remoteRef:
        key: serenditree/app/rootUser/db/password
        property: value
    - secretKey: database_root_password
      remoteRef:
        key: serenditree/app/rootUser/root/password
        property: value
########################################################################################################################
# Database Owner
########################################################################################################################
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.rootUser.db.secretRef }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.rootUser.db.secretRef }}
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: serenditree/app/rootUser/db/user
        property: value
    - secretKey: password
      remoteRef:
        key: serenditree/app/rootUser/db/password
        property: value
########################################################################################################################
# Root
########################################################################################################################
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.rootUser.root.secretRef }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.rootUser.root.secretRef }}
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .Values.rootUser.root.user }}"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: app/rootUser/root/password
        property: value
########################################################################################################################
# Backup
########################################################################################################################
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.rootUser.s3.secretRef }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.rootUser.s3.secretRef }}
    template:
      data:
        ACCESS_REGION: "{{ .Values.global.zone.storage1 }}"
        ACCESS_KEY_ID: "{{ `{{ .ACCESS_KEY_ID }}` }}"
        ACCESS_SECRET_KEY: "{{ `{{ .ACCESS_SECRET_KEY }}` }}"
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: serenditree/iam/backup-user/access
        property: value
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: serenditree/iam/backup-user/secret
        property: value
