---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: branch
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: branch
  data:
    - secretKey: jwk-signature
      remoteRef:
        key: serenditree/app/branch/jwk/signature
        property: value
    - secretKey: jwk-encryption
      remoteRef:
        key: serenditree/app/branch/jwk/encryption
        property: value
    - secretKey: jwk-signature-retiring
      remoteRef:
        key: serenditree/app/branch/jwk/signature/retiring
        property: value
    - secretKey: jwk-encryption-retiring
      remoteRef:
        key: serenditree/app/branch/jwk/encryption/retiring
        property: value
    {{- range .Values.branch.oidc }}
    - secretKey: oidc-id-{{ . }}
      remoteRef:
        key: serenditree/oidc/{{ . }}/id
        property: value
    - secretKey: oidc-secret-{{ . }}
      remoteRef:
        key: serenditree/oidc/{{ . }}/secret
        property: value
    - secretKey: oidc-url-{{ . }}
      remoteRef:
        key: serenditree/oidc/{{ . }}/url
        property: value
    {{- end }}
