---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: github-token
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      data:
        username: "serenditree"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: serenditree/cicd/terraTekton/basic/github
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-token
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: quay-token
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/docker-0: https://quay.io
      data:
        username: "serenditree"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: serenditree/cicd/terraTekton/basic/quay
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-token-oauth
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: quay-token-oauth
    template:
      data:
        token: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: serenditree/cicd/terraTekton/oauth/quay
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redhat-token
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: redhat-token
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/docker-0: https://registry.redhat.io
      data:
        username: "11330181|serenditree"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: serenditree/cicd/terraTekton/basic/redhat
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-token
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-token
    template:
      data:
        ARGOCD_SERVER: "terra-argocd-server.terra-argocd.svc.cluster.local:443"
        ARGOCD_USERNAME: "admin"
        ARGOCD_PASSWORD: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: serenditree/data/cicd/terraArgocd/password
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: slack-webhook
  data:
    - secretKey: webhook
      remoteRef:
        key: serenditree/cicd/terraTekton/webhook/slack
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: github-webhook
  data:
    - secretKey: secret
      remoteRef:
        key: serenditree/cicd/terraTekton/webhook/listener
        property: value
