apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    helm.sh/hook: post-install
spec:
  provider:
    vault:
      server: "http://vault.terra-vault.svc.cluster.local:8200"
      path: serenditree
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-external
          namespace: terra-vault
          key: token
