-- ---------------------------------------------------------------------------------------------------------------------
-- META
-- ---------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Meta" (
    key      VARCHAR(64) NOT NULL,
    value    VARCHAR(64) NOT NULL,
    created  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (key),
    CONSTRAINT unique_meta_key UNIQUE (key)
);

INSERT INTO "Meta" (key, value)
VALUES ('version', '0.0.1')
ON CONFLICT (key) DO UPDATE
SET value    = '0.0.1',
    modified = CURRENT_TIMESTAMP;

SELECT *
FROM "Meta";

-- ---------------------------------------------------------------------------------------------------------------------
-- USER
-- ---------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "User" (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created  TIMESTAMP(6),
    modified TIMESTAMP(6),
    email    VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_user_username UNIQUE (username),
    CONSTRAINT unique_user_email UNIQUE (email)
);

SELECT *
FROM "User"
LIMIT 10;

-- ---------------------------------------------------------------------------------------------------------------------
-- ROLE
-- ---------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Role" (
    "userId"   BIGINT,
    "roleType" VARCHAR(255),
    PRIMARY KEY ("userId", "roleType"),
    CONSTRAINT fk_role_user_id
    FOREIGN KEY ("userId") REFERENCES "User" (id) ON DELETE CASCADE,
    CONSTRAINT check_role_role_type
    CHECK (
        ("roleType")::TEXT = ANY ((
            ARRAY [
            'USER'::CHARACTER VARYING,
            'HUMAN'::CHARACTER VARYING,
            'EDITOR'::CHARACTER VARYING,
            'ADMIN'::CHARACTER VARYING,
            'SYSTEM'::CHARACTER VARYING
            ])::TEXT[]
        )
    )
);

SELECT *
FROM "Role"
LIMIT 10;

-- ---------------------------------------------------------------------------------------------------------------------
-- POLL
-- ---------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Poll" (
    id       UUID,
    title    VARCHAR(255) NOT NULL,
    "userId" BIGINT NOT NULL,
    "seedId" VARCHAR(255) NOT NULL,
    created  TIMESTAMP(6),
    modified TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_poll_seed_id
ON "Poll" ("seedId");

SELECT *
FROM "Poll"
LIMIT 10;

-- ---------------------------------------------------------------------------------------------------------------------
-- POLL OPTION
-- ---------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "PollOption" (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "pollId" UUID,
    text     VARCHAR(255) NOT NULL,
    votes    INTEGER NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_poll_option_poll_id
    FOREIGN KEY ("pollId") REFERENCES "Poll" (id) ON DELETE CASCADE
);

SELECT *
FROM "PollOption"
LIMIT 10;

-- ---------------------------------------------------------------------------------------------------------------------
-- FENCE RECORD
-- ---------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "FenceRecord" (
    "userId"   BIGINT,
    "entityId" VARCHAR(255),
    action     VARCHAR(255),
    expiration TIMESTAMP(6),
    PRIMARY KEY ("userId", "entityId", action, expiration)
);

CREATE INDEX IF NOT EXISTS idx_fence_record_entity_id
ON "FenceRecord" ("entityId");
CREATE INDEX IF NOT EXISTS idx_fence_record_expiration
ON "FenceRecord" (expiration);

SELECT *
FROM "FenceRecord"
LIMIT 10;

-- ---------------------------------------------------------------------------------------------------------------------
-- FENCE ID RECORD
-- ---------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "FenceIdRecord" (
    subject VARCHAR(255),
    PRIMARY KEY (subject)
);

SELECT *
FROM "FenceIdRecord"
LIMIT 10;

-- ---------------------------------------------------------------------------------------------------------------------
-- PRIVILEGES
-- ---------------------------------------------------------------------------------------------------------------------
GRANT ALL PRIVILEGES ON DATABASE "serenditree" TO "serenditree";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "serenditree";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "serenditree";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "serenditree";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "serenditree";
