apiVersion: v2
type: application
name: terra-scope
description: VictoriaMetrics, VictoriaLogs and VictoriaTraces resources.
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: victoria-metrics-k8s-stack
    repository: https://victoriametrics.github.io/helm-charts
    version: 0.92.1
  - name: prometheus-operator-crds
    repository: https://prometheus-community.github.io/helm-charts
    version: 32.0.0
  - name: commons
    repository: oci://quay.io/serenditree/charts
    version: 0.0.1
    condition: global.wait
