apiVersion: v2
type: application
name: terra-streams
description: Strimzi resources.
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts
    version: 1.2.0
  - name: commons
    repository: oci://quay.io/serenditree/charts
    version: 0.0.1
    condition: global.wait
