---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    template:
      data:
        username: "admin"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: serenditree/o11y/terraScope/password
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-api-url
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: slack-api-url
  data:
    - secretKey: slack-api-url
      remoteRef:
        key: serenditree/o11y/terraScope/webhook
        property: value
