---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.rootMap.secret }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.rootMap.secret }}
  data:
    - secretKey: apikey
      remoteRef:
        key: serenditree/iam/data/access
        property: value
    - secretKey: secret
      remoteRef:
        key: serenditree/iam/data/secret
        property: value
