{{- if not (hasSuffix "-local" .Values.global.context) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.terraGateway.name }}
  namespace: {{ .Values.global.argocdNamespace }}
  annotations:
    serenditree.io/wave: {{ .Values.terraGateway.wave | quote }}
    argocd.argoproj.io/sync-wave: {{ .Values.terraGateway.wave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repository | quote }}
    path: "{{ .Values.global.terraPath }}/{{ trimPrefix .Values.global.terraPrefix .Values.terraGateway.name }}"
    targetRevision: {{ .Values.terraGateway.revision | default .Values.global.revision | quote }}
    helm:
      parameters:
        - name: global.wait
          value: {{ .Values.global.wait | quote }}
        - name: global.wave
          value: {{ .Values.terraGateway.wave | quote }}
        - name: global.context
          value: {{ .Values.global.context }}
        - name: global.issuer
          value: {{ .Values.global.issuer }}
        - name: global.host
          value: {{ .Values.global.host }}
        - name: terraGateway.envoy
          value: {{ .Values.terraGateway.parameters.envoy | quote }}
        - name: terraGateway.traefik
          value: {{ .Values.terraGateway.parameters.traefik | quote }}
        - name: terraGateway.loadBalancerID
          value: {{ .Values.terraGateway.parameters.loadBalancerID }}
        - name: terraGateway.cacheHost
          value: "terra-cache.{{ .Values.terraCache.namespace }}.svc.{{ .Values.global.clusterDomain }}:6379"
        - name: gateway-helm.config.envoyGateway.rateLimit.backend.redis.url
          value: "terra-cache.{{ .Values.terraCache.namespace }}.svc.{{ .Values.global.clusterDomain }}:6379"
        - name: traefik.tracing.otlp.grpc.endpoint
          value: "collect.{{ .Values.terraCollect.namespace }}.svc.{{ .Values.global.clusterDomain }}:4317"
        - name: traefik.service.annotations.service\.beta\.kubernetes\.io/exoscale-loadbalancer-id
          value: {{ .Values.terraGateway.parameters.loadBalancerID }}
  destination:
    server: {{ .Values.global.destinationServer }}
    namespace: {{ .Values.terraGateway.namespace }}
  syncPolicy:
    automated: {{ .Values.global.automated | toYaml | nindent 6 }}
    retry: {{ .Values.global.retry | toYaml | nindent 6  }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
