---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.terraVault.name }}
  namespace: {{ .Values.global.argocdNamespace }}
  annotations:
    serenditree.io/wave: {{ .Values.terraVault.wave | quote }}
    argocd.argoproj.io/sync-wave: {{ .Values.terraVault.wave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repository | quote }}
    path: "{{ .Values.global.terraPath }}/{{ trimPrefix .Values.global.terraPrefix .Values.terraVault.name }}"
    targetRevision: {{ .Values.terraVault.revision | default .Values.global.revision | quote }}
    helm:
      parameters:
        - name: global.wait
          value: {{ .Values.global.wait | quote }}
  destination:
    server: {{ .Values.global.destinationServer }}
    namespace: {{ .Values.terraVault.namespace }}
  syncPolicy:
    automated: {{ .Values.global.automated | toYaml | nindent 6 }}
    retry: {{ .Values.global.retry | toYaml | nindent 6  }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - ".spec.volumeClaimTemplates[].metadata.timestamp"
