global:
  zone:
    compute1: ~
  wait: ~
  wave: ~
terraScale:
  enabled: ~
  karpenter: ~
  karpenterReplicas: 0
  clusterAutoscaler: ~
  securityGroup: ~
  privateNetwork: ~
  antiAffinityGroup: ~
  minSize: 3
  maxSize: 6
cluster-autoscaler:
  replicaCount: 1
  autoscalingGroups: []
  cloudProvider: exoscale
  autoDiscovery:
    clusterName: cluster.local
